default_platform(:ios)

platform :ios do
  desc "Build the project"
  lane :build do
    gym(
      scheme: "JobsityChallenge",
      clean: false,
      skip_codesigning: true,
      skip_archive: true,
      skip_package_dependencies_resolution: true,
      )
  end

  desc "Run tests"
  lane :test do
    scan(device: "iPhone 14")
  end

  desc "Runs SwiftLint"
  lane :lint do
    swiftlint
  end

  desc "CI check: build, test and lint"
    lane :ci_check do
      build
      test
      lint
    end
end
